using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Headless-capable asset-bundle build for the Deeroot cards.
///
/// Marks the Time Stop shader into a "deerootcards" bundle, builds it into
/// Assets/AssetBundles, then EMITS its raw bytes as a base64-embedded C#
/// source file inside the mod's asmdef folder — so the plain Unity batch
/// compile (this project's build source of truth) ships the bundle inside
/// DeerootCards.dll itself. No csproj / EmbeddedResource / msbuild step is
/// needed (the template's CsprojPostprocessor route only works for the
/// msbuild flow we don't use).
///
/// Build order (documented in docs/development-notes.md):
///   1) Unity batch with -executeMethod TimeStopBundleBuilder.BuildBundleAndEmitSource
///   2) plain Unity batch compile run — compiles the emitted source into the DLL
/// </summary>
public static class TimeStopBundleBuilder
{
    public const string BundleName = "deerootcards";

    private const string ShaderPath = "Assets/_DeerootCards/Shaders/TimeStopInvert.shader";
    private const string OutDir = "Assets/AssetBundles";
    private const string GeneratedPath = "Assets/_DeerootCards/Code/GeneratedTimeStopAssets.cs";

    [MenuItem("Assets/Build AssetBundles (Time Stop emit)")]
    public static void BuildBundleAndEmitSource()
    {
        var importer = AssetImporter.GetAtPath(ShaderPath);
        if (importer == null)
        {
            Debug.LogError($"[DEER] TimeStop bundle: missing shader at {ShaderPath}");
            return;
        }
        importer.assetBundleName = BundleName;
        importer.SaveAndReimport();

        if (Directory.Exists(OutDir))
        {
            foreach (var file in new DirectoryInfo(OutDir).GetFiles())
            {
                file.Delete();
            }
        }
        else
        {
            Directory.CreateDirectory(OutDir);
        }
        BuildPipeline.BuildAssetBundles(OutDir, BuildAssetBundleOptions.None, BuildTarget.StandaloneWindows);

        string bundleFile = Path.Combine(OutDir, BundleName);
        if (!File.Exists(bundleFile))
        {
            Debug.LogError($"[DEER] TimeStop bundle: build did not produce {bundleFile}");
            return;
        }
        var bytes = File.ReadAllBytes(bundleFile);
        if (bytes.Length == 0)
        {
            Debug.LogError("[DEER] TimeStop bundle: produced bundle is empty");
            return;
        }

        string b64 = Convert.ToBase64String(bytes);
        var sb = new StringBuilder();
        sb.Append("// AUTO-GENERATED by TimeStopBundleBuilder.cs — overwritten on every bundle build. Do not edit by hand.\n");
        sb.Append("// Raw bytes of the '").Append(BundleName).Append("' asset bundle, base64-embedded so the Unity batch compile ships it inside DeerootCards.dll.\n");
        sb.Append("namespace DeerootCards.Cards\n{\n");
        sb.Append("    internal static class GeneratedTimeStopAssets\n    {\n");
        sb.Append("        internal static readonly byte[] BundleBytes = System.Convert.FromBase64String(\n");
        const int chunkSize = 20000;
        for (int i = 0; i < b64.Length; i += chunkSize)
        {
            int len = Math.Min(chunkSize, b64.Length - i);
            bool last = i + chunkSize >= b64.Length;
            sb.Append("            \"").Append(b64.Substring(i, len)).Append('"');
            if (!last)
            {
                sb.Append(" +");
            }
            sb.Append('\n');
        }
        sb.Append("        );\n    }\n}\n");
        File.WriteAllText(GeneratedPath, sb.ToString());
        Debug.Log($"[DEER] TimeStop bundle built ({bytes.Length} bytes) + emitted {GeneratedPath}");
    }
}
